dataset:
  name: vrig-3dprinter
  type: Nerfies
  extension: .png
  source_path: dataset/vrig/vrig-3dprinter/
  mesh_path: dataset/vrig/vrig-3dprinter/mesh.ply
  mesh_alpha: 20
  resolution: 2
  nerfies_type: vrig
  test_per_iter: 5000
model:
  model_path: outputs/vrig-3dprinter
optim:
  batch_size: 2
  opacity_reset_interval: 30000
