dataset:
  name: broom
  type: Nerfies
  extension: .png
  source_path: dataset/vrig/broom/
  mesh_path: dataset/vrig/broom/mesh.ply
  mesh_alpha: 100
  resolution: 2
  nerfies_type: vrig
model:
  model_path: outputs/broom
optim:
  batch_size: 2
  opacity_reset_interval: 30000
