dataset:
  name: curls
  type: Nerfies
  extension: .png
  source_path: dataset/vrig/curls/
  mesh_path: dataset/vrig/curls/mesh.ply
  mesh_alpha: 100
  resolution: 2
  nerfies_type: vrig
model:
  model_path: outputs/curls
optim:
  batch_size: 2
  opacity_reset_interval: 30000
