dataset:
  name: tail
  type: Nerfies
  extension: .png
  source_path: dataset/vrig/tail/
  mesh_path: dataset/vrig/tail/mesh.ply
  mesh_alpha: 20
  resolution: 2
  nerfies_type: vrig
model:
  model_path: outputs/tail
optim:
  batch_size: 2
  opacity_reset_interval: 30000
