dataset:
  name: beagle
  type: Blender
  extension: .png
  source_path: dataset/dg-mesh/beagle/
  mesh_path: dataset/dg-mesh/beagle/train_meshes/r_000.ply
  mesh_alpha: 20
  resolution: 2
model:
  model_path: outputs/beagle
optim:
  batch_size: 2
  opacity_reset_interval: 3000