dataset:
  name: bird
  type: Blender
  extension: .png
  source_path: dataset/dg-mesh/bird/
  mesh_path: dataset/dg-mesh/bird/train_meshes/r_000.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: outputs/bird
optim:
  batch_size: 2