dataset:
  name: duck
  type: Blender
  extension: .png
  source_path: /hdd/msj/dataset/dg-mesh/duck/
  mesh_path: /hdd/msj/dataset/dg-mesh/duck/mesh.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: /hdd2/msj/outputs/duck
optim:
  batch_size: 2
  opacity_reset_interval: 300000