dataset:
  name: duck
  type: Blender
  extension: .png
  source_path: dataset/dg-mesh/duck/
  mesh_path: dataset/dg-mesh/duck/train_meshes/r_000.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: outputs/duck
optim:
  batch_size: 2
  opacity_reset_interval: 300000