dataset:
  name: girlwalk
  type: Blender
  extension: .png
  source_path: dataset/dg-mesh/girlwalk/
  mesh_path: dataset/dg-mesh/girlwalk/train_meshes/r_000.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: outputs/girlwalk
optim:
  batch_size: 5
  opacity_reset_interval: 300000