dataset:
  name: horse
  type: Blender
  extension: .png
  source_path: dataset/dg-mesh/horse/
  mesh_path: dataset/dg-mesh/horse/train_meshes/r_000.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: outputs/horse
optim:
  batch_size: 2