dataset:
  name: horse
  type: Blender
  extension: .png
  source_path: /hdd/msj/dataset/dg-mesh/horse/
  mesh_path: /hdd/msj/dataset/dg-mesh/horse/mesh.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: /hdd2/msj/outputs/horse
optim:
  batch_size: 2