dataset:
  name: torus2sphere
  type: Blender
  extension: .png
  source_path: dataset/dg-mesh/torus2sphere/
  mesh_path: dataset/dg-mesh/torus2sphere/train_meshes/r_000.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: outputs/torus2sphere
optim:
  batch_size: 1
  opacity_reset_interval: 300000