dataset:
  name: bouncingballs
  type: Blender
  extension: .png
  source_path: /hdd/msj/dataset/bouncingballs/
  mesh_path: /hdd/msj/dataset/bouncingballs/mesh.ply
  mesh_alpha: 50
  resolution: 2
model:
  model_path: /hdd2/msj/outputs/bouncingballs
optim:
  batch_size: 2