dataset:
  name: bouncingballs
  type: Blender
  extension: .png
  source_path: dataset/dnerf/bouncingballs/
  mesh_path: dataset/dnerf/bouncingballs/train_meshes/r_000.ply
  mesh_alpha: 50
  resolution: 2
model:
  model_path: outputs/bouncingballs
optim:
  batch_size: 2