dataset:
  name: hellwarrior
  type: Blender
  extension: .png
  source_path: /hdd/msj/dataset/hellwarrior/
  mesh_path: /hdd/msj/dataset/hellwarrior/mesh.ply
  mesh_alpha: 100
  resolution: 2
model:
  model_path: /hdd2/msj/outputs/hellwarrior
optim:
  batch_size: 2