dataset:
  name: jumpingjacks
  type: Blender
  extension: .png
  source_path: dataset/dnerf/jumpingjacks/
  mesh_path: dataset/dnerf/jumpingjacks/train_meshes/r_000.ply
  mesh_alpha: 50
  resolution: 2
model:
  model_path: outputs/jumpingjacks
optim:
  batch_size: 2