dataset:
  name: jumpingjacks
  type: Blender
  extension: .png
  source_path: /hdd/msj/dataset/jumpingjacks/
  mesh_path: /hdd/msj/dataset/jumpingjacks/mesh.ply
  mesh_alpha: 50
  resolution: 2
model:
  model_path: /hdd2/msj/outputs/jumpingjacks
optim:
  batch_size: 2