dataset:
  name: lego
  type: Blender
  extension: .png
  source_path: /hdd/msj/dataset/lego/
  mesh_path: /hdd/msj/dataset/lego/mesh.ply
  mesh_alpha: 30
  resolution: 2
model:
  model_path: /hdd2/msj/outputs/lego
optim:
  batch_size: 1