dataset:
  name: mutant
  type: Blender
  extension: .png
  source_path: dataset/dnerf/mutant/
  mesh_path: dataset/dnerf/mutant/train_meshes/r_000.ply
  mesh_alpha: 40
  resolution: 2
model:
  model_path: outputs/mutant
optim:
  batch_size: 2