dataset:
  name: trex
  type: Blender
  extension: .png
  source_path: /hdd/msj/dataset/trex/
  mesh_path: /hdd/msj/dataset/trex/mesh.ply
  mesh_alpha: 50
  resolution: 2
model:
  model_path: /hdd2/msj/outputs/trex
optim:
  batch_size: 2